openapi: 3.0.3
info:
  title: IT知识问答机器人 API
  description: 基于RAG技术的智能IT知识问答系统
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8080/api/v1
    description: 开发环境
  - url: https://your-domain.com/api/v1
    description: 生产环境

# ============================================
# 安全认证
# ============================================
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # 通用响应
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          description: 响应码
        message:
          type: string
          description: 响应消息
        data:
          type: object
          description: 响应数据
        timestamp:
          type: integer
          description: 时间戳
        requestId:
          type: string
          description: 请求ID

    # 分页响应
    PageResponse:
      type: object
      properties:
        total:
          type: integer
          description: 总记录数
        page:
          type: integer
          description: 当前页码
        size:
          type: integer
          description: 每页大小
        list:
          type: array
          items:
            type: object
          description: 数据列表

    # 用户登录请求
    LoginRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
          description: 用户名
        password:
          type: string
          description: 密码
      example:
        username: "admin"
        password: "admin123"

    # 用户登录响应
    LoginResponse:
      type: object
      properties:
        userId:
          type: integer
        username:
          type: string
        nickname:
          type: string
        role:
          type: string
        token:
          type: string
        expireAt:
          type: integer

    # 用户信息
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        nickname:
          type: string
        email:
          type: string
        avatar:
          type: string
        role:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time

    # 对话会话
    Conversation:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        messageCount:
          type: integer
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    # 消息
    Message:
      type: object
      properties:
        id:
          type: integer
        senderType:
          type: string
          enum: [USER, BOT, SYSTEM]
        content:
          type: string
        metadata:
          type: object
        createdAt:
          type: string
          format: date-time

    # 聊天请求
    ChatRequest:
      type: object
      required: [message]
      properties:
        conversationId:
          type: integer
          description: 对话会话ID,为空则创建新会话
        message:
          type: string
          description: 用户消息
        context:
          type: array
          items:
            type: object
          description: 上下文消息(可选)
      example:
        conversationId: 123
        message: "什么是Spring Boot框架?"

    # 聊天响应
    ChatResponse:
      type: object
      properties:
        messageId:
          type: integer
        answer:
          type: string
        sources:
          type: array
          items:
            $ref: '#/components/schemas/Source'
        usage:
          $ref: '#/components/schemas/TokenUsage'

    # 答案来源
    Source:
      type: object
      properties:
        docId:
          type: integer
        title:
          type: string
        content:
          type: string
        similarity:
          type: number
          format: float
        category:
          type: string

    # Token使用量
    TokenUsage:
      type: object
      properties:
        promptTokens:
          type: integer
        completionTokens:
          type: integer
        totalTokens:
          type: integer

    # 知识库文档
    KnowledgeDoc:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        fileName:
          type: string
        fileSize:
          type: integer
        fileType:
          type: string
        category:
          type: string
        tags:
          type: string
        status:
          type: string
        vectorCount:
          type: integer
        createdBy:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    # 系统配置
    SystemConfig:
      type: object
      properties:
        id:
          type: integer
        configKey:
          type: string
        configValue:
          type: string
        configType:
          type: string
        description:
          type: string
        isEditable:
          type: boolean

# ============================================
# 标签分组
# ============================================
tags:
  - name: 认证
    description: 用户登录认证相关接口
  - name: 聊天
    description: 问答聊天相关接口
  - name: 知识库
    description: 知识库管理相关接口
  - name: 系统配置
    description: 系统配置管理接口
  - name: 用户管理
    description: 用户管理接口(管理员)

# ============================================
# 接口定义
# ============================================
paths:
  # ============================================
  # 认证相关接口
  # ============================================
  /auth/login:
    post:
      tags:
        - 认证
      summary: 用户登录
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/LoginResponse'
        '401':
          description: 用户名或密码错误

  /auth/logout:
    post:
      tags:
        - 认证
      summary: 用户登出
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 登出成功

  /auth/register:
    post:
      tags:
        - 认证
      summary: 用户注册
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password, email]
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                nickname:
                  type: string
      responses:
        '200':
          description: 注册成功

  /auth/profile:
    get:
      tags:
        - 认证
      summary: 获取用户信息
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/User'

  # ============================================
  # 聊天相关接口
  # ============================================
  /chat/message:
    post:
      tags:
        - 聊天
      summary: 发送消息
      description: 发送用户消息并获取AI回答
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: 请求成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/ChatResponse'

  /chat/conversations:
    get:
      tags:
        - 聊天
      summary: 获取对话列表
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          schema:
            type: integer
            default: 10
        - name: status
          in: query
          schema:
            type: string
            enum: [ACTIVE, ARCHIVED, DELETED]
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/PageResponse'

  /chat/conversations/{conversationId}:
    get:
      tags:
        - 聊天
      summary: 获取对话详情
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 获取成功

    delete:
      tags:
        - 聊天
      summary: 删除对话
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 删除成功

  /chat/conversations/{conversationId}/messages:
    get:
      tags:
        - 聊天
      summary: 获取对话消息列表
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 获取成功

  /chat/conversations/{conversationId}/title:
    put:
      tags:
        - 聊天
      summary: 更新对话标题
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
      responses:
        '200':
          description: 更新成功

  # ============================================
  # 知识库管理接口
  # ============================================
  /knowledge/docs:
    get:
      tags:
        - 知识库
      summary: 获取文档列表
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          schema:
            type: integer
            default: 10
        - name: category
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum: [ACTIVE, INACTIVE, PROCESSING, FAILED]
        - name: keyword
          in: query
          schema:
            type: string
            description: 搜索关键词
      responses:
        '200':
          description: 获取成功

    post:
      tags:
        - 知识库
      summary: 上传文档
      security:
        - BearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: 文件
                title:
                  type: string
                  description: 文档标题
                description:
                  type: string
                  description: 文档描述
                category:
                  type: string
                  description: 分类
                tags:
                  type: string
                  description: 标签,逗号分隔
      responses:
        '200':
          description: 上传成功

  /knowledge/docs/{docId}:
    get:
      tags:
        - 知识库
      summary: 获取文档详情
      security:
        - BearerAuth: []
      parameters:
        - name: docId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 获取成功

    put:
      tags:
        - 知识库
      summary: 更新文档信息
      security:
        - BearerAuth: []
      parameters:
        - name: docId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                category:
                  type: string
                tags:
                  type: string
      responses:
        '200':
          description: 更新成功

    delete:
      tags:
        - 知识库
      summary: 删除文档
      security:
        - BearerAuth: []
      parameters:
        - name: docId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 删除成功

  /knowledge/docs/{docId}/reindex:
    post:
      tags:
        - 知识库
      summary: 重新索引文档
      security:
        - BearerAuth: []
      parameters:
        - name: docId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 重新索引已启动

  /knowledge/categories:
    get:
      tags:
        - 知识库
      summary: 获取知识库分类列表
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 获取成功

  # ============================================
  # 系统配置接口
  # ============================================
  /admin/config:
    get:
      tags:
        - 系统配置
      summary: 获取系统配置
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ApiResponse'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/SystemConfig'

    put:
      tags:
        - 系统配置
      summary: 更新系统配置
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                config:
                  type: object
                  description: 配置键值对
      responses:
        '200':
          description: 更新成功

  # ============================================
  # 用户管理接口(管理员)
  # ============================================
  /admin/users:
    get:
      tags:
        - 用户管理
      summary: 获取用户列表
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 获取成功
